<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <Description>Provides utilites and extensions for Quartz.</Description>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Cogito.Autofac.DependencyInjection" Version="6.1.0" />
        <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.12" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.12" />
        <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.12" />
        <PackageReference Include="Quartz" Version="3.22.0" />
        <PackageReference Include="Quartz.Extensions.Hosting" Version="3.22.0" />
        <PackageReference Include="Quartz.Jobs" Version="3.22.0" />
        <PackageReference Include="Quartz.Serialization.Json" Version="3.22.0" />
    </ItemGroup>

</Project>
